- name: checking preference in all types
  hosts: local
  connection: local
  # vars_files:
  # - course.yaml
  # vars:
  #   Name: Play level variable preference check
  # vars_prompt:
  # - name: Name
  #   prompt: What is your Name ?
  #   private: true
  tasks:
  - name: print credentials
    # vars:
    #   Name: Task level preference check
    ansible.builtin.debug:
      msg: "Hello, Name is: {{ Name }}"

