- name: Datatype variables
  hosts: local
  connection: local
  vars:
    Course: AWS DevOps Engineering
    Duration: 10HRS
    is_live: true
  tools:  # ["linux", "shell", "ansible"]
    - linux
    - shell
    - ansible
  concepts:
    cloud: aws
    cm: ansible
  tasks:
    name: print the cource info
    ansible.builtin.debug:
      msg: "Course name is: {{ Course }}, Duration is: {{ Duration }}, is it live?: {{ is_live }}, tools are: {{ tools }}, concepts are: {{ concepts }}"
