- name: install pacakge
  hosts: local
  connection: local
  tasks:
  - name: print pacakges
    ansible.builtin.pacakge:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx
    - zip
    - oracle
