# Converting yaml file into json file
- name: yaml to json and command vs shell demo
  hosts: local
  connection: local
  vars:
    ipaddress: 192.168.1.10

  tasks:
    # Step 1: read yaml file and take it into a variable
    - name: read yaml and take it into a variable
      ansible.builtin.set_fact:
        student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"

    # Step 2: convert yaml into json
    - name: convert yaml into json
      ansible.builtin.debug:
        msg: "json: {{ student_yaml | to_json }}"

    # Step 3: save readable json into a file
    - name: saved into json file
      ansible.builtin.copy:
        dest: ./student-data.json
        content: "{{ student_yaml | to_nice_json }}"

    # check IP address valid or not
    - name: checking IP_Address Valid or Not
      ansible.builtin.debug:
        msg: "{{ ipaddress | ansible.utils.ipv4 }}"

    # grep for root using command module (pipe work avvadu, fail avthundi)
    - name: grep for root using command module
      ansible.builtin.command: cat /etc/passwd | grep root
      register: command_output
      ignore_errors: true

    - name: print the command_output
      ansible.builtin.debug:
        msg: "{{ command_output }}"

    # grep for root using shell module
    - name: grep for root using shell module
      ansible.builtin.shell: cat /etc/passwd | grep root
      register: shell_output

    - name: print the shell_output
      ansible.builtin.debug:
        msg: "{{ shell_output }}"

    # redirect using command module (fail avthundi)
    - name: redirect the output command module
      ansible.builtin.command: ls -lts > /tmp/output.txt
      register: redirect_output
      ignore_errors: true

    - name: print redirect output command module
      ansible.builtin.debug:
        msg: "{{ redirect_output }}"

    # redirect using shell module (work avthundi)
    - name: redirect output shell module
      ansible.builtin.shell: ls -lts > /tmp/output.txt
      register: redirect_shell_output

    - name: print redirect output using shell module
      ansible.builtin.debug:
        msg: "{{ redirect_shell_output }}"


